site_name: CUDA Tutorial
pages:
  - 'Home': 'index.md'
  - 'Tutorials':
    - 'Tutorial 01: Say Hello to CUDA': 'tutorials/tutorial01/index.md'
    - 'Tutorial 02: CUDA in Actions': 'tutorials/tutorial02/index.md'
theme: readthedocs
markdown_extensions:
  - markdown.extensions.extra

  
